// Ben M, ChatGPT
// Updated for TBA generated JSON
// 3-6-2026
// Reads match_data.json generated by MatchDataGenerator

package org.iowacityrobotics.rebuiltscoutingapp2026.data;

import android.content.Context;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;

public class MatchSchedule {

    public static JSONArray matchesArray;

    public static void loadSchedule(Context context) {

        try {

            File file = new File(context.getFilesDir(), "match_data.json");

            FileInputStream fis = new FileInputStream(file);

            byte[] buffer = new byte[(int) file.length()];
            fis.read(buffer);
            fis.close();

            String jsonString =
                    new String(buffer, StandardCharsets.UTF_8);

            JSONObject jsonObject =
                    new JSONObject(jsonString);

            matchesArray =
                    jsonObject.getJSONArray("matches");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static String getTeamNumber(
            String matchNumStr,
            String assignment,
            String matchType
    ) {

        if (matchesArray == null ||
                matchNumStr.isEmpty() ||
                assignment == null ||
                matchType == null)
            return "";

        try {

            int matchId = Integer.parseInt(matchNumStr);

            for (int i = 0; i < matchesArray.length(); i++) {

                JSONObject match =
                        matchesArray.getJSONObject(i);

                if (match.getInt("match_id") == matchId &&
                        match.getString("match_type")
                                .equalsIgnoreCase(matchType)) {

                    String allianceKey =
                            assignment.contains("Red")
                                    ? "red_alliance"
                                    : "blue_alliance";

                    String digitOnly =
                            assignment.replaceAll("[^0-9]", "");

                    if (digitOnly.isEmpty())
                        return "";

                    int index =
                            Integer.parseInt(digitOnly) - 1;

                    JSONArray allianceArray =
                            match.getJSONArray(allianceKey);

                    if (index >= 0 &&
                            index < allianceArray.length()) {

                        return String.valueOf(
                                allianceArray.getInt(index)
                        );
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return "";
    }
}